### ISSUE TITLE
Today, with the News HASS Version, i don't find my Kostal Device.

### ISSUE THREAD

**Issue by markusleins** [gieljnssns/kostalpiko-sensor-homeassistant#18]
**Describe the bug**

**Any errors**
```
error here
```

**Config yaml**
```
yaml here
```

**Screenshots**

**Additional context**

**Comment by markusleins** [comment]
What ist the Problem Here?

Logger: homeassistant.components.sensor
Source: util/async_.py:139
Integration: Sensor (documentation, issues)
First occurred: 19:47:55 (1 occurrences)
Last logged: 19:47:55

Error while setting up kostal platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/kostal/sensor.py", line 31, in async_setup_entry
    data = PikoData(piko, hass)
  File "/config/custom_components/kostal/sensor.py", line 236, in __init__
    self.info_update()
  File "/config/custom_components/kostal/sensor.py", line 250, in info_update
    self.info = self.piko._get_info()
  File "/usr/local/lib/python3.8/site-packages/kostalpyko/kostalpyko.py", line 219, in _get_info
    r = requests.get(url, auth=(login, pwd), timeout=15)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 150, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 139, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/kostal/sensor.py, line 250: self.info = self.piko._get_info()

**Comment by gieljnssns** [comment]
You should try this custom component https://github.com/rcasula/kostalpiko-homeassistant
My Kostal inverter is broken so I can't test any new versions

**Comment by feutl** [comment]
All which is needed is adding a "version" to the manifest.json
https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/

had the same issue, fixed by manually adding this.

@gieljnssns 
would like to jump onto the "alternative" but the manifest is wrong too and even the readme.md is not filled. So does not seem like there is any development happening.

But thanks for the addon anyhow.

**Comment by tampicoscott** [comment]
> All which is needed is adding a "version" to the manifest.json
> https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/
> 
> had the same issue, fixed by manually adding this.
> 
> @gieljnssns
> would like to jump onto the "alternative" but the manifest is wrong too and even the readme.md is not filled. So does not seem like there is any development happening.
> 
> But thanks for the addon anyhow.

Hi,
If I add "version": "1.0.0", to the manifest.json and then restart HA, it is not working.
Any suggestions?
Maybe the version is wrong?
Thanks

**Comment by Od1waN** [comment]
> All which is needed is adding a "version" to the manifest.json
> https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/
> 
> had the same issue, fixed by manually adding this.
> 
> @gieljnssns
> would like to jump onto the "alternative" but the manifest is wrong too and even the readme.md is not filled. So does not seem like there is any development happening.
> 
> But thanks for the addon anyhow.

Hey, how you add this version string? i add the version but it is ignored from HA or i have to reboot after i add the version? Can you explain please?

*edit*
This plugin is working again, how to!
1. remove this plugin from HACS
2. comment out the kostal entrys in the configuration.yaml
3. soft reboot HA
4. install kostal repo with HACS
5. using file edit and move to custom_components/kostal - manifest.json
6. "domain": "kostal",
    "name": "Kostal",
    "version": "v2.7",
7. soft reboot HA
8. remove comments from configuration
9. soft reboot HA

**Comment by feutl** [comment]
so, just for me, all I did was rename the manifest and reboot
![image](https://user-images.githubusercontent.com/8522012/121857079-837d1a80-ccf5-11eb-90f7-fc9f1aa288eb.png)

**Comment by Datatekniker** [comment]
Worked for me as well.

JUST add the Version in the manifest.json

:-)

**Comment by passi16** [comment]
Worked for me as well :-)
