### ISSUE TITLE
Error while setting up Kostal component

### ISSUE THREAD

**Issue by birdie60** [gieljnssns/kostalpiko-sensor-homeassistant#2]
Hello,
after I installed your kostal component via hacs, and configured it in sensors.yaml, I restarted homeassistant. Now I got this in the logs:
```
2019-11-12 17:39:09 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform kostal
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/kostal/sensor.py", line 57, in setup_platform
    from kostalpyko.kostalpyko import Piko
  File "/srv/homeassistant/lib/python3.7/site-packages/kostalpyko/kostalpyko.py", line 6, in <module>
    from lxml import html
ModuleNotFoundError: No module named 'lxml'
```

Anything I could try? I'm running on hassbian, with latest homeassistant version.

**Comment by gieljnssns** [comment]
Can you try v2.2 in HACS?

**Comment by birdie60** [comment]
Yes, that did it, kostal component is now showing up in my HA interface! Thanks a lot for developing and sharing this component!
